import "./globals.css";
import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import bg from "./../../public/statics/pictures/backgroung.jpg";
import { ReduxProvider } from "@/redux/provider";
import Head from "next/head";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Filimo Movie List</title>
        <Link
          rel="preload"
          href={"/public/statics/fonts/ttf/IRANSansWeb.ttf"}
          as={"font"}
        />
      </Head>
      <body className={inter.className}>
        <ReduxProvider>
          <div style={{ position: "fixed", height: "100vh", width: "100vw" }}>
            <Image
              // priority
              alt="background"
              src={bg}
              fill
              style={{
                backgroundColor: "rgba(12, 12, 12, 0.85)",
                opacity: 0.05,
                zIndex: "-1000",
              }}
            ></Image>
          </div>

          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
